<?php
class Rental{
    private $conn; private $table='rental';
    public $rental_id; public $customer_id; public $costume_id; public $start_date; public $end_date; public $quantity; public $total_amount; public $payment_status; public $status; public $penalty_fee;
    public function __construct($db){ $this->conn=$db; }
    public function all(){ $stmt = $this->conn->query("SELECT r.*, c.customer_name, co.costume_category FROM {$this->table} r LEFT JOIN customer c ON r.customer_id=c.customer_id LEFT JOIN costume co ON r.costume_id=co.costume_id"); return $stmt->fetchAll(PDO::FETCH_ASSOC); }
    public function find($id){ $stmt=$this->conn->prepare("SELECT * FROM {$this->table} WHERE rental_id=:id"); $stmt->execute(array(':id'=>$id)); return $stmt->fetch(PDO::FETCH_ASSOC); }
    public function create(){ $sql = "INSERT INTO {$this->table} (customer_id,costume_id,start_date,end_date,quantity,total_amount,payment_status,status,penalty_fee) VALUES (:customer_id,:costume_id,:start_date,:end_date,:quantity,:total_amount,:payment_status,:status,:penalty_fee)"; $stmt=$this->conn->prepare($sql); return $stmt->execute(array(':customer_id'=>$this->customer_id,':costume_id'=>$this->costume_id,':start_date'=>$this->start_date,':end_date'=>$this->end_date,':quantity'=>$this->quantity,':total_amount'=>$this->total_amount,':payment_status'=>$this->payment_status,':status'=>$this->status,':penalty_fee'=>$this->penalty_fee)); }
    public function update($id){ $sql = "UPDATE {$this->table} SET customer_id=:customer_id,costume_id=:costume_id,start_date=:start_date,end_date=:end_date,quantity=:quantity,total_amount=:total_amount,payment_status=:payment_status,status=:status,penalty_fee=:penalty_fee WHERE rental_id=:id"; $stmt=$this->conn->prepare($sql); return $stmt->execute(array(':customer_id'=>$this->customer_id,':costume_id'=>$this->costume_id,':start_date'=>$this->start_date,':end_date'=>$this->end_date,':quantity'=>$this->quantity,':total_amount'=>$this->total_amount,':payment_status'=>$this->payment_status,':status'=>$this->status,':penalty_fee'=>$this->penalty_fee,':id'=>$id)); }
    public function delete($id){ $stmt=$this->conn->prepare("DELETE FROM {$this->table} WHERE rental_id=:id"); return $stmt->execute(array(':id'=>$id)); }
}
